client_config_backend: settings
client_config:
  client_id: 87570657756-j9hm6gkbq6kksbanamq789b5pp0ml9nv.apps.googleusercontent.com
  client_secret: C3EF3Bpn_32ScoxYh7f9rfwh

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials/credentials_drive.json

get_refresh_token: False

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
