"""story and buyers table

Revision ID: 3a77a9bcd849
Revises: 
Create Date: 2020-06-15 14:57:00.725513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a77a9bcd849'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address_1', sa.String(length=120), nullable=True),
    sa.Column('address_2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_email'), 'buyer', ['email'], unique=True)
    op.create_index(op.f('ix_buyer_first_name'), 'buyer', ['first_name'], unique=False)
    op.create_index(op.f('ix_buyer_last_name'), 'buyer', ['last_name'], unique=False)
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('nickname_gender', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('dog', sa.String(length=64), nullable=True),
    sa.Column('friend', sa.String(length=64), nullable=True),
    sa.Column('friend_gender', sa.String(length=64), nullable=True),
    sa.Column('cake', sa.String(length=64), nullable=True),
    sa.Column('cake_gender', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('album', sa.String(length=2083), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_timestamp'), 'story', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_timestamp'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_buyer_last_name'), table_name='buyer')
    op.drop_index(op.f('ix_buyer_first_name'), table_name='buyer')
    op.drop_index(op.f('ix_buyer_email'), table_name='buyer')
    op.drop_table('buyer')
    # ### end Alembic commands ###
