"""empty message

Revision ID: 63f4d570500b
Revises: 8a21296378cf
Create Date: 2020-05-11 21:14:12.879464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f4d570500b'
down_revision = '8a21296378cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('album', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'album')
    # ### end Alembic commands ###
