"""add album link

Revision ID: cfe49b942672
Revises: 3a77a9bcd849
Create Date: 2020-08-23 16:52:26.996724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe49b942672'
down_revision = '3a77a9bcd849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('cover', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'cover')
    # ### end Alembic commands ###
